In [51]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files

In [2]:
df = pd.read_csv('/content/car_price_performance.csv')

In [46]:
brand_avg_price = df.groupby('Brand')['Price'].mean().sort_values()
brand_mapping = {brand: i for i, brand in enumerate(brand_avg_price.index, start=1)}
df['Encoded_Brand'] = df['Brand'].map(brand_mapping)
print("\nEncoded Brand values:")
print(df[['Brand', 'Encoded_Brand']].drop_duplicates())
df

Encoded Brand values:
      Brand  Encoded_Brand
0   Brand C              6
1   Brand A              4
3   Brand E              2
4   Brand X              8
5   Brand W              1
6   Brand Y              3
9   Brand D              9
12  Brand B              5
13  Brand Z              7

,Brand,Price,Horsepower,Fuel Efficiency,Brand_Encoded,Encoded_Brand,Scaled_Horsepower,Scaled_Brand,Scaled_Fuel_Efficiency,Performance_Index
0,Brand C,91942,0.7050,0.212,0.625,6,0.7050,0.625,0.212,0.14946
1,Brand A,70075,0.2425,0.904,0.375,4,0.2425,0.375,0.904,0.21922
2,Brand C,84524,0.2200,0.996,0.625,6,0.2200,0.625,0.996,0.21912
3,Brand E,68939,0.3950,0.204,0.125,2,0.3950,0.125,0.204,0.08058
4,Brand X,66505,0.4425,0.120,0.875,8,0.4425,0.875,0.120,0.05310
...,...,...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,0.2400,0.208,0.750,7,0.2400,0.750,0.208,0.04992
1996,Brand C,35215,0.6925,0.612,0.625,6,0.6925,0.625,0.612,0.42381
1997,Brand E,72980,0.4850,0.472,0.125,2,0.4850,0.125,0.472,0.22892
1998,Brand Z,55921,0.8575,0.040,0.750,7,0.8575,0.750,0.040,0.03430
1999,Brand B,95051,0.3125,0.096,0.500,5,0.3125,0.500,0.096,0.03000

In [23]:
def min_max_scale(series):
    return (series - series.min()) / (series.max() - series.min())

In [19]:
df['Scaled_Horsepower'] = min_max_scale(df['Horsepower'])

In [22]:
print(df.columns)
df['Scaled_Fuel_Efficiency'] = min_max_scale(df['Fuel Efficiency'])

Index(['Brand', 'Price', 'Horsepower', 'Fuel Efficiency', 'Brand_Encoded',
       'Encoded_Brand', 'Scaled_Horsepower', 'Scaled_Brand'],
      dtype='object')

In [21]:
df['Scaled_Brand'] = min_max_scale(df['Encoded_Brand'])

In [47]:
df['Performance_Index'] = df['Horsepower'] * df['Fuel Efficiency']
print(df['Performance_Index'])
df

0       0.14946
1       0.21922
2       0.21912
3       0.08058
4       0.05310
         ...
1995    0.04992
1996    0.42381
1997    0.22892
1998    0.03430
1999    0.03000
Name: Performance_Index, Length: 2000, dtype: float64

,Brand,Price,Horsepower,Fuel Efficiency,Brand_Encoded,Encoded_Brand,Scaled_Horsepower,Scaled_Brand,Scaled_Fuel_Efficiency,Performance_Index
0,Brand C,91942,0.7050,0.212,0.625,6,0.7050,0.625,0.212,0.14946
1,Brand A,70075,0.2425,0.904,0.375,4,0.2425,0.375,0.904,0.21922
2,Brand C,84524,0.2200,0.996,0.625,6,0.2200,0.625,0.996,0.21912
3,Brand E,68939,0.3950,0.204,0.125,2,0.3950,0.125,0.204,0.08058
4,Brand X,66505,0.4425,0.120,0.875,8,0.4425,0.875,0.120,0.05310
...,...,...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,0.2400,0.208,0.750,7,0.2400,0.750,0.208,0.04992
1996,Brand C,35215,0.6925,0.612,0.625,6,0.6925,0.625,0.612,0.42381
1997,Brand E,72980,0.4850,0.472,0.125,2,0.4850,0.125,0.472,0.22892
1998,Brand Z,55921,0.8575,0.040,0.750,7,0.8575,0.750,0.040,0.03430
1999,Brand B,95051,0.3125,0.096,0.500,5,0.3125,0.500,0.096,0.03000

In [48]:
final_df = df[['Brand', 'Price', 'Horsepower', 'Fuel Efficiency',
               'Encoded_Brand', 'Scaled_Horsepower',
               'Scaled_Fuel_Efficiency', 'Scaled_Brand', 'Performance_Index']]
final_df.head()

,Brand,Price,Horsepower,Fuel Efficiency,Encoded_Brand,Scaled_Horsepower,Scaled_Fuel_Efficiency,Scaled_Brand,Performance_Index
0,Brand C,91942,0.7050,0.212,6,0.7050,0.212,0.625,0.14946
1,Brand A,70075,0.2425,0.904,4,0.2425,0.904,0.375,0.21922
2,Brand C,84524,0.2200,0.996,6,0.2200,0.996,0.625,0.21912
3,Brand E,68939,0.3950,0.204,2,0.3950,0.204,0.125,0.08058
4,Brand X,66505,0.4425,0.120,8,0.4425,0.120,0.875,0.05310

In [52]:
final_df.to_csv('scaled_car_data.csv', index=False)
files.download('scaled_car_data.csv')